name: 'Action Testing'
description: 'Testing'
inputs:
  owner:
    description: 'The owner of the repository'
    required: false
  repo:
    description: 'The name of the repository'
    required: false
  pr_number:
    description: 'The number of the pull request'
    required: false
  token:
    description: 'The token to use to access the GitHub API'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
