
name: Manual workflow
on:
  workflow_dispatch:

jobs:
  execBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Git
    #   run: |
    #     git config --local user.name "ooling"
    #     git config --local user.email "samooling@gmail.com"
    #     git clone "https://github.com/SamXuLing.git" targetRepo
    # - name: Run index.mjs
    #   run: node index.mjs
    #   env:
    #     TEST: ${{ secrets.TESTINGSECRET }}
    - name: Git
      run: cd .git
      # run: |
      #   git add ./index.html
      #   git commit -m "Test Commit"
      #   git push
