
name: Manual workflow
on:
  workflow_dispatch:

jobs:
  execBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Worker
      env:
        SECRET_AUTH: ${{ secrets.SECRET_AUTH }}
      run: node index.mjs
