
name: Manual workflow
on:
  workflow_dispatch:

jobs:
  execBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run index.js
      run: node index.js
      env:
        TEST: ${{ secrets.TESTINGSECRET }}
