
name: Manual workflow
on:
  workflow_dispatch:

jobs:
  execBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run index.mjs
      run: node index.mjs
      env:
        TEST: ${{ secrets.TESTINGSECRET }}
    - name: Git
      run: |
        git status
        git add ./index.html
        git commit -m "Test Commit"
        git push
