
name: Manual workflow
on:
  workflow_dispatch:

jobs:
  execBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Stage 1
      run: |
        git config --local hub.protocol https
        git config --local user.name "ooling"
        git config --local user.email "samooling@gmail.com"
        git clone "https://github.com/ooling/SamXuLing.git" targetRepo
    - name: Stage 2
      env:
        TEST: ${{ secrets.TESTINGSECRET }}
      run: node index.mjs
    - name: Stage 3
      run: |
        ls
        cd targetRepo
        ls
      # run: |
      #   git add ./index.html
      #   git commit -m "Test Commit"
      #   git push
